### ISSUE TITLE
400 bad request when calling validate on specific text

### ISSUE THREAD

**Issue by jamieburchell** [jabranr/postcodes-io#12]
Call `validate('Willoughby Hedge')` and you'll get a 400 bad request from `file_get_contents()`. Change it to `validate('Willoughby hedge')` and you'll get back the expected response object with result `false`.

When I used Postman directly to call the API, both worked:

`https://api.postcodes.io/postcodes/Willoughby Hedge/validate`:

```
{
    "status": 200,
    "result": false
}
```

`https://api.postcodes.io/postcodes/Willoughby hedge/validate`

```
{
    "status": 200,
    "result": false
}
```

This issue can be reproduced outside of the library:

```
$ php -r "echo file_get_contents('https://api.postcodes.io/postcodes/Willoughby Hedge/validate');"

PHP Warning:  file_get_contents(https://api.postcodes.io/postcodes/Willoughby Hedge/validate): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. file_get_contents($filename = 'https://api.postcodes.io/postcodes/Willoughby Hedge/validate') Command line code:1

$ php -r "echo file_get_contents('https://api.postcodes.io/postcodes/Willoughby hedge/validate');"
{"status":200,"result":false}
```

If you urlencode the space, the problem is resolved:

```
$ php -r "echo file_get_contents('https://api.postcodes.io/postcodes/Willoughby%20Hedge/validate');"
{"status":200,"result":false}
```

Also, if your postcode contains a slash `/` the request fails, so this should be urlencoded too (`rawurlencode`).

PHP 8.1.0

**Comment by jabranr** [comment]
Hi @jamieburchell thank you for reporting this. Would you like to send a PR for this? I will be happy to review and merge.

**Comment by jamieburchell** [comment]
Hi @jabranr I'm not sure how you would like to go about it. It seems that every parameter that could be part of the final URL needs to be `rawurlencode`'d

**Comment by jabranr** [comment]
No worries. I think I might get some time to work on these and set up some CI pipelines to run tests periodically.
