### ISSUE TITLE
Possibly incorrect parameter order

### ISSUE THREAD

**Issue by jamieburchell** [jabranr/postcodes-io#14]
I think random should be after %s here?

https://github.com/jabranr/postcodes-io/blob/ddfaa36bcba1f36fc48d4740d2e8a14d689ccd9d/src/PostcodesIO.php#L41

**Comment by jamieburchell** [comment]
Hey @jabranr I apologise - I misunderstood that the end result should have been /random/postcodes after all so this wasn't an issue in the first place :/

**Comment by jabranr** [comment]
@jamieburchell No worries. However, I found that `%s` substitution was adding an extra `/` because the value of constant `API_POSTCODES_ENDPOINT` is `/postcodes` – so I have changed it from `/random/%s` to `/random%s`.
