### ISSUE TITLE
PHP warning when file_get_contents gets a non 200 response

### ISSUE THREAD

**Issue by jamieburchell** [jabranr/postcodes-io#5]
I'm wondering if this warning can/should be suppressed given the response error message is checked and an exception is thrown. One method might simply be to prefix the call with a *gasp* @ symbol.

I noticed cURL is used for POST but not GET; perhaps more control would be had using cURL for GET too?

**Comment by jabranr** [comment]
@jamieburchell Thank you for pointing it out. I did not put `@` in front it intentionally so to not have it failed silently. Could you please provide an example to reproduce this failure?

**Comment by jamieburchell** [comment]
H!, yes simply call for example the find method with an invalid postcode. If error reporting and display errors are configured you should see a PHP warning. In production at least this could mean a PHP warning in the logs for something which you are already handling as an error by checking the response. I'm not saying I'm right, just to me the warning seems pointless here.

**Comment by jamieburchell** [comment]
Also if you do switch to a package such as Guzzle you have more flexibility. For anyone who doesn't support remote file_get_contents for example.

**Comment by jabranr** [comment]
Closing this as it will be addressed in other issues.

**Comment by jabranr** [comment]
Partially related to #9
